FROM golang:1.13.10-alpine3.11

COPY . /teamup
ENV GOPROXY "https://goproxy.cn"


RUN apk add git \
    && git clone https://github.com/micro/micro /micro \
    && cd /micro/cmd/protoc-gen-micro \
    && go build . && chmod +x protoc-gen-micro \
    && mv protoc-gen-micro /bin

RUN cd /teamup \
    && go get github.com/golang/protobuf/proto \
    && go get github.com/golang/protobuf/protoc-gen-go \
    && go mod download

RUN cd /teamup/user \
    && go build -o user-service . \
    && chmod +x /teamup/user/user-service


WORKDIR /teamup/user

CMD ["./user-service"]
