version: '2'
services:
  user-service:
    image: teamup-user:latest
    restart: always
    environment:
      - GO_RUN_MODE=product
  activity-service:
    image: teamup-activity:latest
    restart: always
    environment:
      - GO_RUN_MODE=product
  api-gateway:
    image: teamup-api:latest
    restart: always
    ports:
      - 8888:8888
    environment:
      - GO_RUN_MODE=product
