// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package teamup_svc_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRes) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetUserInfoReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserInfo struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "teamup.svc.user.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "teamup.svc.user.LoginRes")
	proto.RegisterType((*GetUserInfoReq)(nil), "teamup.svc.user.getUserInfoReq")
	proto.RegisterType((*UserInfo)(nil), "teamup.svc.user.UserInfo")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4e, 0xc3, 0x30,
	0x0c, 0xc6, 0x55, 0x46, 0xa7, 0xce, 0x93, 0x00, 0x59, 0x08, 0x8d, 0x1d, 0x60, 0xca, 0xa9, 0xa7,
	0x1c, 0xe0, 0x0c, 0x47, 0xa4, 0x4a, 0x9c, 0x82, 0x78, 0x80, 0xd0, 0x99, 0x6a, 0x82, 0x26, 0x23,
	0x49, 0xfb, 0x2a, 0xbc, 0x2e, 0x72, 0x9a, 0x56, 0xfc, 0xdb, 0xcd, 0x5f, 0xfc, 0xb3, 0x3f, 0x7f,
	0x0a, 0x40, 0xe7, 0xc9, 0xc9, 0xbd, 0xb3, 0xc1, 0xe2, 0x69, 0x20, 0xdd, 0x76, 0x7b, 0xe9, 0xfb,
	0x5a, 0xf2, 0xb3, 0xb8, 0x82, 0xe2, 0xd1, 0x36, 0x3b, 0xa3, 0xe8, 0x03, 0x11, 0x8e, 0x6b, 0xbb,
	0xa5, 0x55, 0xb6, 0xc9, 0xca, 0x85, 0x8a, 0xb5, 0x78, 0x98, 0xfa, 0x1e, 0xcf, 0x21, 0x0f, 0xf6,
	0x8d, 0x4c, 0x02, 0x06, 0x31, 0x4d, 0x1d, 0x6d, 0xb2, 0x32, 0x1f, 0xa6, 0xf0, 0x0c, 0x66, 0xad,
	0x6f, 0x56, 0xb3, 0xc8, 0x71, 0x29, 0x4a, 0x38, 0x69, 0x28, 0x3c, 0x7b, 0x72, 0x95, 0x79, 0xb5,
	0xec, 0x76, 0x01, 0x73, 0xbe, 0xa0, 0xda, 0xc6, 0x75, 0xb9, 0x4a, 0x4a, 0xdc, 0x43, 0x31, 0x62,
	0xcc, 0xe8, 0x5e, 0x07, 0xed, 0x92, 0x65, 0x52, 0xb8, 0x86, 0x82, 0x69, 0xa3, 0xdb, 0xc1, 0x77,
	0xa1, 0x26, 0x7d, 0xf3, 0x99, 0xc1, 0x92, 0x17, 0x3c, 0x91, 0xeb, 0x77, 0x35, 0xe1, 0x1d, 0xe4,
	0xef, 0x9c, 0x00, 0x2f, 0xe5, 0xaf, 0xf0, 0x72, 0x4c, 0xbe, 0x3e, 0xd8, 0xf2, 0x58, 0xc1, 0xf2,
	0xdb, 0xe1, 0x78, 0xfd, 0x87, 0xfc, 0x19, 0xeb, 0x9f, 0x55, 0x63, 0xf7, 0x65, 0x1e, 0xff, 0xe0,
	0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x89, 0xa1, 0xc1, 0x91, 0x01, 0x00, 0x00,
}
